sonar.projectKey=ml-platform
sonar.projectName=ML Inference Platform
sonar.projectVersion=1.0.0

sonar.sources=app/
sonar.tests=tests/
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/tests/**,**/__pycache__/**,**/migrations/**
